const KEY="zumurda_products_v1";let list=load();
function load(){try{const x=JSON.parse(localStorage.getItem(KEY));return Array.isArray(x)?x:DEFAULT_PRODUCTS.map(x=>({...x}))}catch{return DEFAULT_PRODUCTS.map(x=>({...x}))}}
function save(){localStorage.setItem(KEY,JSON.stringify(list))}
function label(c){return ({makeup:"مكياج",care:"عناية",perfume:"عطور",accessories:"إكسسوارات",gifts:"هدايا",boxes:"بوكسات",offers:"عروض"})[c]||c}
function render(){document.querySelector("#productCount").textContent=list.length;document.querySelector("#adminProducts").innerHTML=list.map(p=>`<div class="admin-item"><img src="${p.image}" alt=""><div><strong>${p.name}</strong><small>${label(p.category)} • ${new Intl.NumberFormat("ar-SY").format(p.price)} ل.س</small></div><div class="item-actions"><button data-edit="${p.id}">تعديل</button><button class="delete" data-delete="${p.id}">حذف</button></div></div>`).join("")}
function resetForm(){document.querySelector("#productForm").reset();document.querySelector("#formTitle").textContent="إضافة منتج";document.querySelector('[name=id]').value=""}
document.querySelector("#productForm").addEventListener("submit",e=>{e.preventDefault();const d=Object.fromEntries(new FormData(e.currentTarget));d.id=d.id.trim()||d.name.toLowerCase().replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"")+"-"+Date.now();d.price=Number(d.price);d.categoryName=label(d.category);d.recipients=["friend","sister","special"];d.occasions=["birthday","visit","none"];const old=list.findIndex(p=>p.id===d.id);if(old>=0)list[old]={...list[old],...d};else list.unshift(d);save();render();resetForm();alert("تم حفظ المنتج")});
document.querySelector("#adminProducts").addEventListener("click",e=>{const ed=e.target.closest("[data-edit]"),del=e.target.closest("[data-delete]");if(ed){const p=list.find(x=>x.id===ed.dataset.edit);if(!p)return;for(const k of ["id","name","category","price","image","tag","budget"])document.querySelector(`[name="${k}"]`).value=p[k]??"";document.querySelector("#formTitle").textContent="تعديل منتج";window.scrollTo({top:0,behavior:"smooth"})}if(del&&confirm("حذف هذا المنتج؟")){list=list.filter(x=>x.id!==del.dataset.delete);save();render()}});
document.querySelector("#cancelEdit").addEventListener("click",resetForm);
document.querySelector("#restoreBtn").addEventListener("click",()=>{if(confirm("سيتم استبدال المنتجات الحالية بالمنتجات التجريبية. متابعة؟")){list=DEFAULT_PRODUCTS.map(x=>({...x}));save();render()}});
render();