window.DEFAULT_PRODUCTS = [
{id:"rose-box",name:"بوكس روزي الناعم",category:"boxes",categoryName:"بوكسات",price:185000,tag:"الأكثر طلباً",recipients:["friend","sister","fiance","special"],occasions:["birthday","visit","anniversary"],budget:"premium",image:"https://images.unsplash.com/photo-1549465220-1a8b9238cd48?auto=format&fit=crop&w=900&q=85"},
{id:"velvet-perfume",name:"عطر Velvet Rose",category:"perfume",categoryName:"عطور",price:135000,tag:"جديد",recipients:["fiance","friend","special"],occasions:["birthday","anniversary"],budget:"medium",image:"https://images.unsplash.com/photo-1541643600914-78b084683601?auto=format&fit=crop&w=900&q=85"},
{id:"soft-lip",name:"مجموعة Soft Lip",category:"makeup",categoryName:"مكياج",price:75000,tag:"اختيار ذكي",recipients:["friend","sister","fiance"],occasions:["birthday","graduation","none"],budget:"low",image:"https://images.unsplash.com/photo-1586495777744-4413f21062fa?auto=format&fit=crop&w=900&q=85"},
{id:"pearl-set",name:"طقم لؤلؤي يومي",category:"accessories",categoryName:"إكسسوارات",price:110000,tag:"أناقة هادئة",recipients:["mother","friend","sister","special"],occasions:["birthday","visit","none"],budget:"medium",image:"https://images.unsplash.com/photo-1611652022419-a9419f74343d?auto=format&fit=crop&w=900&q=85"},
{id:"care-moment",name:"بوكس عناية وراحة",category:"care",categoryName:"عناية",price:125000,tag:"للحظات الهادئة",recipients:["mother","friend","sister"],occasions:["birthday","visit","none"],budget:"medium",image:"https://images.unsplash.com/photo-1571781926291-c477ebfd024b?auto=format&fit=crop&w=900&q=85"},
{id:"mini-gift",name:"هدية صغيرة بفرحة كبيرة",category:"gifts",categoryName:"هدايا",price:65000,tag:"اقتصادية",recipients:["friend","sister","special"],occasions:["birthday","visit","graduation","none"],budget:"low",image:"https://images.unsplash.com/photo-1513883049090-d0b7439799bf?auto=format&fit=crop&w=900&q=85"},
{id:"glow-kit",name:"Glow Beauty Kit",category:"makeup",categoryName:"مكياج",price:160000,tag:"مميز",recipients:["fiance","friend","sister"],occasions:["birthday","graduation","anniversary"],budget:"premium",image:"https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?auto=format&fit=crop&w=900&q=85"},
{id:"gold-offer",name:"عرض العناية الذهبي",category:"offers",categoryName:"عروض",price:99000,tag:"عرض",recipients:["mother","friend","sister","special"],occasions:["birthday","visit","none"],budget:"medium",image:"https://images.unsplash.com/photo-1556228578-8c89e6adf883?auto=format&fit=crop&w=900&q=85"}
];